package com.example.carter.cisc_325_calendar;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.support.design.widget.FloatingActionButton;
import android.support.design.widget.Snackbar;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.util.Log;
import android.view.KeyEvent;
import android.view.LayoutInflater;
import android.view.View;
import android.view.Menu;
import android.view.MenuItem;
import android.view.ViewGroup;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ListView;
import android.widget.TextView;
import android.widget.Toast;

import java.util.ArrayList;
import java.util.List;

public class AddNames extends AppCompatActivity {
    private EditText emailInpt; //textbox at top of screen
    ArrayList<String> list = new ArrayList<>(); //basically the back-end of adapter. Use adapter.add instead of list.add
    ArrayAdapter<String> adapter; //an android thing for displaying listViews on screen

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        Log.d("", "logcat is working YAAAAHHH!!!!");
        //initialization stuff
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_add_names);

        //get references to objects created in content_add_names.xml
        emailInpt = (EditText) findViewById(R.id.emailInpt);
        ListView emailList = (ListView) findViewById(R.id.emailList);

        //TODO: set onSubmit here

        adapter = new MyListAdapter(this, R.layout.list_item, list); //hook adapter up to the ArrayList list
        emailList.setAdapter(adapter); //hook adapter up to the ListView emailList

        Button button = (Button) findViewById((R.id.button));
        //on click, add blank email to emailList (there's a callback below that instantiates the input field and remove button)
        button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                adapter.add("");
                Log.d("", "added a thing");
            }
        });

        //when enter is pressed
        /*
        emailInpt.setOnEditorActionListener(new TextView.OnEditorActionListener() {
            @Override
            public boolean onEditorAction(TextView v, int actionId, KeyEvent event) {
                String input = emailInpt.getText().toString();
                if (list.size() == 0 && input.length() > 0) {
                    adapter.add(v); //should hold something more substantial
                }
                return false;
            }
        });
        */

        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        //stuff for handling the pink mail icon in the bottom-right corner
        FloatingActionButton fab = (FloatingActionButton) findViewById(R.id.fab);
        fab.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                /*
                //this was auto generated by android studio
                Snackbar.make(view, "Replace with your own action", Snackbar.LENGTH_LONG)
                        .setAction("Action", null).show();
                */
                //switch activities to GenerateAvailability.java
                Intent myIntent = new Intent(view.getContext(), GenerateAvailability.class);
                startActivity(myIntent);
            }
        });
    }
    //more android studio generated stuff
    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_add_names, menu);
        return true;
    }

    //android studio generated
    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            return true;
        }

        return super.onOptionsItemSelected(item);
    }

    //This allows the buttons in the list to be clickable
    private class MyListAdapter extends ArrayAdapter<String> {
        private int layout;
        public MyListAdapter(Context context, int resource, List<String> objects) {
            super(context, resource, objects);
            layout = resource; //in our case this is R.layout.list_item, which is an xml layout I made
        }

        //called when an object from the list comes on screen (I think)
        @Override
        public View getView(int position, View convertView, ViewGroup parent) {
            Log.d("", "view ran, I guess that's good");
            if (convertView == null) { //if item in ListView emailList hasn't been initialized
                LayoutInflater inflater = LayoutInflater.from(getContext());
                convertView = inflater.inflate(layout, parent, false); //initialize it
                EditText inpt = (EditText) convertView.findViewById(R.id.emailInpt); //fetches EditText object, but I'm not sure how
                inpt.setOnEditorActionListener(new TextView.OnEditorActionListener() {
                    @Override
                    public boolean onEditorAction(TextView v, int actionId, KeyEvent event) { //when user edits an email text entry
                        String input = v.getText().toString();
                        Log.d("", input); //prints inpt, for debugging
                        if (input.equals("")) {
                            adapter.remove("");
                            // move this element from the array
                        } else if (list.indexOf("") == list.size()-1) {
                            adapter.add(""); //removes last element FIX THIS
                        }
                        return false;
                    }
                });
                Button minus = (Button) convertView.findViewById(R.id.minus);
                minus.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {

                        list.remove(""); //remove this element from the array
                        notifyDataSetChanged();
                    }
                });
            }
            return convertView;
        }
    }
}
